import Head from 'next/head'
import NavBar from '../components/Navbar'

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      {/* <div className='m-10 space-x-4 flex flex-wrap items-center'>
        {data.map((item) => {
          return (
            <>
              // Card 
              <div className='h-full w-[20rem] shadow-xl p-7'>
                <p>Issue Status: {item.state ? 'Open' : 'Closed'}</p>
                <p>Issue Title: {item.title}</p>
                <a href={item.html_url} className="decoration-3 underline">Click here</a>
                // badges 
                <p className='mt-4'>Labels:</p>
                <div className='flex flex-wrap space-x-2'>
                  {item.labels.map((label) => {
                    return (
                      <div className='bg-[#f1e05a] text-black rounded-md p-2'>
                        {label.name}
                      </div>
                    )
                  })}
                </div>
                <div className='flex flex-around items-center space-x-5 mt-5 w-full h-full'>
                  <img src={item.user.avatar_url} className="h-10 w-10 rounded-full" alt="" />
                  <p>{item.user.login}</p>
                </div>
              </div>
            </>
          )
        })}
      </div> */}

      {/* <div>
        <div className='h-[20rem] w-[20rem] shadow-xl p-5'>
          <p> 'Issue Open' : 'Issue Closed'</p>
        </div>
      </div> */}

    </div>
  )
}

// export const getServerSideProps = async (context) => {
//   const data = await (await fetch('http://localhost:5000/get')).json()
//   return {
//     props: { data }
//   }
// }

export default Home
